plc_kfe_gmd_vac.tmc
==================

Errors
------
```
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.7.1/bin/pytmc", line 10, in <module>
    sys.exit(main())
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/pytmc/bin/pytmc.py", line 92, in main
    func(**kwargs)
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/pytmc/bin/db.py", line 271, in main
    show_error_context=not no_error_context,
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/pytmc/bin/db.py", line 110, in process
    for symbol in find_pytmc_symbols(tmc, allow_no_pragma=allow_no_pragma)
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/pytmc/bin/db.py", line 112, in <listcomp>
    symbol, yield_exceptions=True, allow_no_pragma=allow_no_pragma)
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/pytmc/pragmas.py", line 593, in record_packages_from_symbol
    allow_no_pragma=allow_no_pragma):
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/pytmc/pragmas.py", line 584, in chains_from_symbol
    full_chain, allow_no_pragma=allow_no_pragma):
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/pytmc/pragmas.py", line 249, in expand_configurations_from_chain
    result.append(list(dictify_func(item)))
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/pytmc/pragmas.py", line 217, in dictify_scalar
    split_pytmc_pragma('\n'.join(pragmas))):
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/pytmc/pragmas.py", line 83, in split_pytmc_pragma
    result = [_LINE_PARSER.search(m).groupdict() for m in result_no_delims]
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/pytmc/pragmas.py", line 83, in <listcomp>
    result = [_LINE_PARSER.search(m).groupdict() for m in result_no_delims]
AttributeError: 'NoneType' object has no attribute 'groupdict'
```

Records
-------
```
```

EPICS database
--------------
```
```
